catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
]

main_app/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("cats/", views.CatsList.as_view(), name="cats_index"),
    path("cats/<int:pk>/", views.detail, name="cats_detail"),
    path("cats/create/", views.CatsCreate.as_view(), name="cats_create"),
    path("cats/<int:pk>/update/", views.CatsUpdate.as_view(), name="cats_update"),
    path("cats/<int:pk>/feeding/", views.add_feeding, name="cats_feeding"),
    path("cats/<int:pk>/delete/", views.CatsDelete.as_view(), name="cats_delete"),
    path("cats/<int:cat_id>/toy/<int:toy_id>/associate", views.assoc_toy, name="assoc_toy"),
    path("cats/<int:cat_id>/toy/<int:toy_id>/disassociate", views.disassoc_toy, name="disassoc_toy"),
]

main_app/models.py
import datetime
from django.db import models
from django.urls import reverse

class Toy(models.Model):
    name = models.CharField(max_length=64, default="no name")
    color = models.CharField(max_length=64, default="no color")

    def __str__(self):
        return f"{self.color} {self.name}"

    def get_html_name(self):
        return "<span style='color:" + self.color + ";'>" + self.color.title() + \
            "</span> " + self.name.title()


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:cats_detail", kwargs={"pk": self.id})

MEALS = (
    ('B', "Breakfast"),
    ('L', "Lunch"),
    ('D', "Dinner"),
)

class Feeding(models.Model):
    date = models.DateField(default=datetime.date.today)
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]  # 'B'
    )
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding, Cat


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ["date", "meal"]

class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = ["name", "breed", "description", "age"]

main_app/views.py
from . import models
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from .forms import FeedingForm, CatForm
from .models import Cat, Toy


def home(request):
    return render(request, "cats/home.html", {})

def about(request):
    return render(request, "about.html", {})

def add_feeding(request, pk):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = pk
        new_feeding.save()
    return redirect('main:cats_detail', pk = pk)


def detail(request, pk):
    cat = Cat.objects.get(id=pk)

    toys_have_ids = cat.toys.all().values_list('id')
    toys_not_have = Toy.objects.exclude(id__in=toys_have_ids)
    feeding_form = FeedingForm()
    return render(request, "cats/detail.html", {
        "feeding_form": feeding_form,
        "toys_not_have": toys_not_have,
        "cat": cat,
    })

class CatsList(ListView):
    model = models.Cat
    template_name = "cats/index.html"
    context_object_name = "cats"

    def get_queryset(self):
        return get_list_or_404(models.Cat)

class CatsCreate(CreateView):
    model = models.Cat
    fields = "__all__"
    success_url = '/cats'

    def get_form_class(self):
        return CatForm


class CatsUpdate(UpdateView):
    model = models.Cat
    fields = ["breed", "description", "age"]
    success_url = "/cats"

    def get_form_class(self):
        return CatForm

class CatsDelete(DeleteView):
    model = models.Cat
    success_url = "/cats"

def disassoc_toy(request, cat_id, toy_id):
    cat = get_object_or_404(Cat, id=cat_id)
    toy = get_object_or_404(Toy, id=toy_id)
    cat.toys.remove(toy)
    return redirect("main:cats_detail", pk=cat_id)

def assoc_toy(request, cat_id, toy_id):
    cat = get_object_or_404(Cat, id=cat_id)
    toy = get_object_or_404(Toy, id=toy_id)
    cat.toys.add(toy)
    return redirect("main:cats_detail", pk=cat_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About the Cat Collector</h1>
<hr>
<p>Hire the Cat Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cat Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
<header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <ul>
                <li><a href="{% url 'main:home' %}" class="left brand-logo">&nbsp;&nbsp;Cat Collector</a></li>
            </ul>
            <ul class="right">
                <li><a href="{% url 'main:about' %}">About</a></li>
                <li><a href="{% url 'main:cats_create' %}">Add a Cat</a></li>
                <li><a href="{% url 'main:cats_index' %}">View All My Cats</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
<footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Cat Collector &nbsp;</div>
</footer>
</body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Cat Details</h1>

    <section class="row">
        {# Display general cat info #}
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ cat.name }}</span>
                    <p>breed: {{ cat.breed }}</p>
                    <p>description:</p>
                    <p>{{ cat.description }}</p>
                    {% if cat.age > 0 %}
                        <p>age: {{ cat.age }}</p>
                    {% else %}
                        <p>age: Kitten</p>
                    {% endif %}
                </div>

                <div class="card-action">
                    <a href="{% url 'main:cats_update' cat.id %}">Edit</a>
                    <a href="{% url 'main:cats_delete' cat.id %}">Delete</a>
                </div>
            </div>
        </div>

        {# Display feeding #}
        <div class="col s6">
            <form action="{% url 'main:cats_feeding' cat.id %}" method="POST">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" class="btn" value="Add Feeding">
            </form>
            <table class="striped">
                <thead>
                    <tr><th>Date</th><th>Meal</th></tr>
                </thead>
                <tbody>
                    {% for feeding in cat.feeding_set.all %}
                        <tr>
                            <td>{{ feeding.date }}</td>
                            <td>{{ feeding.get_meal_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>

    <hr/>

    <section>
        <h3>Toys</h3>
        <div class="row">
            <div class="col s6">
                {# Display cat's toys here #}
                <h4>{{ cat.name }}'s</h4>
                {% if cat.toys.count %}
                    {% for toy in cat.toys.all %}
                        <div class="card">
                            <div class="card-content">
                                <h2 class="card-title">
                                    {% autoescape off %}
                                        {{ toy.get_html_name }}
                                    {% endautoescape %}
                                </h2>
                            </div>
                            <div class="card-action">
                                <form action="{% url 'main:disassoc_toy' cat.id toy.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn red">Remove</button>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No Toys</p>
                {% endif %}
            </div>
            <div class="col s6">
                <h4>Available</h4>
                {% if toys_not_have.count %}
                    {% for toy in toys_not_have.all %}
                        <article class="card">
                            <div class="card-content">
                                <h2 class="card-title">
                                    {% autoescape off %}
                                        {{ toy.get_html_name }}
                                    {% endautoescape %}
                                </h2>
                            </div>
                            <div class="card-action">
                                <form action="{% url 'main:assoc_toy' cat.id toy.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn">Add</button>
                                </form>

                            </div>
                        </article>
                    {% endfor %}
                {% else %}
                    <p>None available.</p>
                {% endif %}
            </div>
        </div>
    </section>

    <script>
        window.addEventListener("load", () => {
            const dateEl = document.getElementById("id_date");
            M.Datepicker.init(dateEl, {
                format: 'yyyy-mm-dd',
                defaultDate: new Date(),
                setDefaultDate: true,
                autoClose: true,
            });

            const selectEl = document.getElementById("id_meal");
            M.FormSelect.init(selectEl);
        });

    </script>
{% endblock %}

main_app/templates/cats/home.html
{% extends 'base.html' %}
<h1>Hello world!</h1>

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Cat List</h1>

    {% for cat in cats %}
        <article class="card">
            <div class="card-content">
                <a href="{{ cat.get_absolute_url }}">
                    <span class="card-title">{{ cat.name }}</span>
                </a>

                <p>Breed: {{ cat.breed }}</p>
                <p>Description: {{ cat.description }}</p>
                {% if cat.age > 0 %}
                    <p>Age: {{ cat.age }}</p>
                {% else %}
                    <p>Age: Kitten</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'main:cats_update' cat.id %}">Edit</a>
                <a href="{% url 'main:cats_delete' cat.id %}">Delete</a>
            </div>
        </article>
    {% endfor %}

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Cat</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="YES - DELETE!" class="btn" />
        <a href="{% url 'main:cats_detail' cat.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% block content %}
    {% if object %}
        <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
        <h1>Add Cat</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}